version: '3'

tasks:
  build:
    desc: Build the goralph binary
    cmds:
      - go build -o goralph .

  run:
    desc: Run the main.go application
    cmds:
      - go run main.go

  install:
    desc: Install goralph to ~/.local/bin/
    deps: [build]
    cmds:
      - mkdir -p ~/.local/bin
      - cp goralph ~/.local/bin/
